# Generated by Django 3.0.7 on 2020-07-02 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name_text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_text', models.CharField(max_length=255)),
                ('last_modified', models.DateTimeField(verbose_name='last modified')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timer_app.ProjectName')),
            ],
        ),
    ]
