# Generated by Django 3.0.7 on 2020-07-02 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timer_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectName',
            new_name='Project',
        ),
    ]
