# Generated by Django 3.0.7 on 2020-07-03 15:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer_app', '0002_auto_20200702_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 3, 10, 48, 22, 806335), verbose_name='last modified'),
        ),
        migrations.AddField(
            model_name='project',
            name='time_text',
            field=models.CharField(default='0:0:0', max_length=255),
        ),
        migrations.DeleteModel(
            name='Time',
        ),
    ]
