# Generated by Django 3.0.7 on 2020-07-03 15:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer_app', '0003_auto_20200703_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 3, 10, 51, 0, 491222), verbose_name='last modified'),
        ),
    ]
